# Site Build Settings
tittle:                  Christian Albia
tagline:
description:
baseurl:                 #"/ChristianAlbia"  
url:                     #"https://Christian20b.github.io"
github:
url:                     #"https://Christian20b.github.io/ChristianAlbia"
author:
  name:                  "Christian"
  email:                 "calbia7@gmail.com"
  instagram:             "adoniz10"
  github:                "Christian20b"
  facebook:              "Christian Albia"
navigation:
-title: ¿Quién soy yo?
  url: /about
-title: Publicaciones
  url: /writing
-title: Contacto
  url: /contact         
# Jekyll-paginate-v2 configuration
#  pagination:
#   enabled: true
#   per_page: 5
#   permalink: '/page/:num/'
#   title: ':title - page :num of :max'
#   limit: 0
#   sort_field: 'date'
#   sort_reverse: true

# jekyll-paginate configuration
paginate:            5

# Build settings
markdown:            kramdown
highlighter:         rouge
permalink:           none
plugins:             [jekyll-paginate, jekyll-sitemap, jekyll-feed, jekyll-seo-tag]

# Customise atom feed settings (this is where Jekyll-Feed gets configuration information)
title:		           'Lagrange'
description:	       'a minimalist Jekyll theme'
author:              'Paul Le'

# RSS 2.0 can be used instead of Atom by uncommenting following two lines
#feed:
#  path: rss-feed.xml
